import requests

res = requests.get("https://randomuser.me/api/")
print(res.status_code)
print(res.headers)
print(res.request)
print(res.reason)
print(res.url)
print(res.cookies)
print(res.elapsed)
print(res.encoding)
print(res.history)
print(res.raw)
print(res.__dict__)
# print(res.__annotations__)
print(res.__attrs__)
# print(res.__slots__)
print(res.__doc__)
print(res.__module__)
print(res.links)
print(res.next)
print(res.ok)
print(res.content)
print(res.text)
print(res.apparent_encoding)
print(res.is_permanent_redirect)
print(res.is_redirect)


